Alien[] alienArray;
Bullet[] doubleBulletArray;
Player thePlayer;
Bullet theBullet;
DoubleBullet doubleBullet;
SoundFile shootSound;
SoundFile explodeSound;
SoundFile bulletCatch;
SoundFile playerDeath;
PImage alienImage;
PImage bulletCounter;
PImage doubleBulletBoosterImage;
PImage playerImage;
PImage bulletImage;
PImage doubleBulletImage;
PImage backgroundImage;
PImage alienCounter;
PImage bulletBoostImage;
PImage explodeImage;
PImage disappearImage;
boolean drawBullet;
boolean drawDoubleBullet;
boolean doubleBulletFire;
boolean endGame;
boolean startGame;
boolean leftPressed;
boolean rightPressed;
int xPos = 1;
int yPos = 50;
int aliensRemaining;
int bulletsRemaining;
int doubleBulletsRemaining;
int amountOfAliens =100;
int SCREEN_X=1280;
int SCREEN_Y=720;